# Ona/Gitpod Configuration for JetBrains IDE
# https://www.gitpod.io/docs/references/gitpod-yml

image:
  file: .devcontainer/Dockerfile

tasks:
  - name: Setup Environment
    init: |
      echo "✅ Ona JetBrains environment initialized"
    command: |
      echo "🚀 Ona JetBrains Environment Ready!"
      echo "📦 Node: $(node --version)"
      echo "🐍 Python: $(python --version)"
      echo ""
      echo "Available services:"
      echo "  Port 3000 - Dev Server"
      echo "  Port 5000 - Flask API"
      echo "  Port 8000 - FastAPI"
      echo "  Port 8888 - Jupyter"
      echo "  Port 11434 - Ollama"
      echo ""

  - name: Ollama (Optional)
    command: |
      if command -v ollama &> /dev/null; then
        echo "🦙 Starting Ollama..."
        ollama serve
      else
        echo "ℹ️  Ollama not installed. Run: curl -fsSL https://ollama.com/install.sh | sh"
      fi

ports:
  - port: 3000
    onOpen: notify
    name: Dev Server
  - port: 5000
    onOpen: notify
    name: Flask API
  - port: 8000
    onOpen: notify
    name: FastAPI
  - port: 8080
    onOpen: notify
    name: Proxy
  - port: 8888
    onOpen: notify
    name: Jupyter
  - port: 11434
    onOpen: ignore
    name: Ollama

jetbrains:
  intellij:
    plugins:
      - PythonCore
      - JavaScript
      - org.jetbrains.plugins.yaml
      - com.intellij.database
      - org.intellij.plugins.markdown
      - com.jetbrains.restClient
      - Docker
      - com.intellij.kubernetes
      - org.intellij.plugins.hcl
      - org.toml.lang
      - com.intellij.plugins.vscodekeymap
      - com.intellij.java
      - org.jetbrains.kotlin
      - com.intellij.jupyter
    prebuilds:
      version: stable
  pycharm:
    plugins:
      - com.intellij.database
      - com.jetbrains.restClient
      - com.intellij.jupyter
      - org.intellij.plugins.yaml
      - Docker
      - com.intellij.kubernetes
      - org.intellij.plugins.markdown
    prebuilds:
      version: stable
  webstorm:
    plugins:
      - JavaScript
      - org.jetbrains.plugins.yaml
      - org.intellij.plugins.markdown
      - Docker
    prebuilds:
      version: stable

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - ms-python.python
    - GitHub.copilot
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools

github:
  prebuilds:
    main: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
